export const PAGES = {
  home: '/',
  chatWithUs: '/chat-with-us',
  blog: '/blog',
  tags: '/tags',
  categories: '/categories',
  aboutUs: '/about-us',
  careers: '/careers',
  profile: '/profile',
  products: '/products',
  signup: '/signup',
  cart: '/cart',
  help: '/help',
  search: '/search'
}

export const API = {
  categories: '/categories',
  categories_add: '/categories/add',
  products: '/products',
  products_filters: '/products/filters',
  products_comments: '/products/comments',
  products_reviewQuestions_count: '/products/review-questions/count',
  products_add: '/products/add',
  products_add_review: '/products/add/review',
  tags: '/tags',
  tags_add: '/tags/add',
  auth_signup: '/auth/signup',
  auth_login: '/auth/login',
  auth_logout: '/auth/logout',
  auth_refresh: '/auth/refresh',
  user_updateProfile: '/user/update-profile',
  user_products_ids: '/user/products/ids',
  user_wishlist_add: '/user/wishlist/add',
  user_wishlist_remove: '/user/wishlist/remove',
  user_compare_add: '/user/compare/add',
  user_compare_remove: '/user/compare/remove',
  user_cart_add: '/user/cart/add',
  user_cart_remove: '/user/cart/remove',
  customerReviews: '/customer-reviews',
  customerReviews_add: '/customer-reviews/add',
  blogPosts: '/blog-posts',
  blogPosts_add: '/blog-posts/add'
}
