export const ROUTES = {
  home: '/',
  chat: '/chat-with-us',
  blog: '/blog',
  tags: '/tags',
  categories: '/categories',
  about: '/about-us',
  careers: '/careers',
  profile: '/profile',
  signup: '/signup',
  cart: '/cart',
  products: '/products',
  products_comments: '/products/comments',
  add_product_review: '/products/add/review',
  questions_reviews_count: '/products/reviews-questions/count',
  help: '/help',
  search: '/search',
  customers_reviews: '/customer-reviews',
  blog_posts: '/blog-posts',
  auth_login: '/auth/login',
  auth_signup: '/auth/signup',
  auth_logout: '/auth/logout',
  auth_refresh: '/auth/refresh',
  user_update_profile: '/user/update-profile'
}
