export { default as CartTemplate } from './CartTemplate/CartTemplate'
export { default as ProductCategoryTemplate } from './categories/ProductCategoryTemplate/ProductCategoryTemplate'
export { default as CheckoutTemplate } from './CheckoutTemplate/CheckoutTemplate'
export { default as HomeTemplate } from './HomeTemplate/HomeTemplate'
export { default as ProductTemplate } from './products/ProductTemplate/ProductTemplate'
export { default as ProfileTemplate } from './ProfileTemplate/ProfileTemplate'
export { default as SignupTemplate } from './SignupTemplate/SignupTemplate'
